-- MySQL Script generated by MySQL Workbench
-- 07/24/15 19:52:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`user_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_no` VARCHAR(45) NULL COMMENT '    - Admin > 1\n    - Manager > 2\n    - It support > 3\n    - User > 4',
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_no` VARCHAR(20) NULL,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(60) NULL,
  `remember_token` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  `avatar` TEXT NULL,
  `create_user` INT NULL,
  `created_at` DATETIME NULL,
  `update_user` INT NULL,
  `updated_at` DATETIME NULL,
  `flag` INT NULL,
  `user_role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_role_id`),
  INDEX `fk_user_user_role1_idx` (`user_role_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `laravel`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`device_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`device_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_no` VARCHAR(45) NULL,
  `brand` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `ip_address` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `serial_no` VARCHAR(100) NULL,
  `warranty` VARCHAR(45) NULL,
  `amount` INT NULL,
  `unit_price` VARCHAR(45) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `stock_id` INT UNSIGNED NOT NULL,
  `device_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `stock_id`, `device_type_id`),
  INDEX `fk_device_stock1_idx` (`stock_id` ASC),
  INDEX `fk_device_devicel_type1_idx` (`device_type_id` ASC),
  CONSTRAINT `fk_device_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `laravel`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_devicel_type1`
    FOREIGN KEY (`device_type_id`)
    REFERENCES `laravel`.`device_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`material_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`material_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `material_no` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `serial_no` VARCHAR(100) NULL,
  `warranty` VARCHAR(45) NULL,
  `amount` INT NULL,
  `unit_price` VARCHAR(45) NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `stock_id` INT UNSIGNED NOT NULL,
  `material_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `stock_id`, `material_type_id`),
  INDEX `fk_material_stock1_idx` (`stock_id` ASC),
  INDEX `fk_material_material_type1_idx` (`material_type_id` ASC),
  CONSTRAINT `fk_material_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `laravel`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_material_type1`
    FOREIGN KEY (`material_type_id`)
    REFERENCES `laravel`.`material_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`repair_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`repair_device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `repair_no` VARCHAR(45) NULL,
  `person` INT NULL,
  `approvement` TINYINT(1) NULL,
  `approved_date` DATETIME NULL,
  `received_by` INT NULL,
  `received_date` DATETIME NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`booking_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`booking_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `booking_no` VARCHAR(45) NULL,
  `events` VARCHAR(200) NULL,
  `purpose` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `contact_person` INT NULL,
  `email` VARCHAR(100) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `room_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `room_id`),
  INDEX `fk_booking_room_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_booking_room_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `laravel`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`lend_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`lend_device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lend_no` VARCHAR(45) NULL,
  `purpose` VARCHAR(200) NULL,
  `rent_person` INT NULL,
  `email` VARCHAR(100) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `approvement` TINYINT(1) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`repair_device_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`repair_device_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `symptom` TEXT NULL,
  `flag` INT NULL,
  `repair_device_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `repair_device_id`, `device_id`),
  INDEX `fk_repair_device_detail_repair_device1_idx` (`repair_device_id` ASC),
  INDEX `fk_repair_device_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_repair_device_detail_repair_device1`
    FOREIGN KEY (`repair_device_id`)
    REFERENCES `laravel`.`repair_device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_device_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`lend_device_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`lend_device_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `flag` INT NULL,
  `lend_device_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `lend_device_id`, `device_id`),
  INDEX `fk_booking_device_detail_booking_device1_idx` (`lend_device_id` ASC),
  INDEX `fk_booking_device_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_booking_device_detail_booking_device1`
    FOREIGN KEY (`lend_device_id`)
    REFERENCES `laravel`.`lend_device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_device_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(45) NULL,
  `purpose` VARCHAR(200) NULL,
  `order_by` INT NULL,
  `order_date` DATETIME NULL,
  `approvement` TINYINT(1) NULL,
  `approved_date` DATETIME NULL,
  `received_by` INT NULL,
  `received_date` DATETIME NULL,
  `checked_by` INT NULL,
  `checked_date` DATE NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`order_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_no` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `amount` INT NULL,
  `unit_price` VARCHAR(45) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  INDEX `fk_order_detail_order_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_detail_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `laravel`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`mapping_computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`mapping_computer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mapping_no` VARCHAR(45) NULL,
  `computer_name` VARCHAR(100) NULL,
  `serial_no` VARCHAR(100) NULL,
  `ip` VARCHAR(45) NULL,
  `os` VARCHAR(45) NULL,
  `product_key_os` VARCHAR(45) NULL,
  `brand` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `cpu` VARCHAR(100) NULL,
  `ram` VARCHAR(100) NULL,
  `video_card` VARCHAR(100) NULL,
  `hdd` VARCHAR(100) NULL,
  `cd_dvd` VARCHAR(100) NULL,
  `antivirus` TINYINT(1) NULL,
  `status` TINYINT(1) NULL,
  `room` VARCHAR(45) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `room_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `room_id`),
  INDEX `fk_mapping_computer_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_mapping_computer_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `laravel`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`booking_room_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`booking_room_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `flag` INT NULL,
  `booking_room_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `booking_room_id`, `device_id`),
  INDEX `fk_booking_room_detail_booking_room1_idx` (`booking_room_id` ASC),
  INDEX `fk_booking_room_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_booking_room_detail_booking_room1`
    FOREIGN KEY (`booking_room_id`)
    REFERENCES `laravel`.`booking_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_room_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`bring_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`bring_material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bring_no` VARCHAR(45) NULL,
  `purpose` VARCHAR(200) NULL,
  `description` VARCHAR(45) NULL,
  `withdraw_person` INT NULL,
  `email` VARCHAR(100) NULL,
  `approvement` TINYINT(1) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`bring_material_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`bring_material_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `status` TINYINT(1) NULL,
  `flag` INT NULL,
  `bring_material_id` INT UNSIGNED NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `bring_material_id`, `material_id`),
  INDEX `fk_bring_material_detail_bring_material1_idx` (`bring_material_id` ASC),
  INDEX `fk_bring_material_detail_material1_idx` (`material_id` ASC),
  CONSTRAINT `fk_bring_material_detail_bring_material1`
    FOREIGN KEY (`bring_material_id`)
    REFERENCES `laravel`.`bring_material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bring_material_detail_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `laravel`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`user_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`user_stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `flag` INT NULL,
  `stock_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `stock_id`, `users_id`),
  INDEX `fk_user_stock_stock1_idx` (`stock_id` ASC),
  INDEX `fk_user_stock_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_stock_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `laravel`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_stock_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `laravel`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`running_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`running_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL COMMENT '    - order > 1\n    - booking room > 2\n    - bring material > 3 \n    - lend device > 4\n    - repair device > 5\n    - mapping computer > 6\n    - request booking room > 7\n    - request repair > 8\n    - request other > 9',
  `number` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_no` VARCHAR(45) NULL,
  `contact_person` INT NULL,
  `assign_person` INT NULL,
  `topic` VARCHAR(200) NULL,
  `events` VARCHAR(200) NULL,
  `room` INT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `description` TEXT NULL,
  `priority` INT NULL COMMENT '    - Highest > 5\n    - High > 4\n    - Normal > 3\n    - Some > 2\n    - A little > 1',
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `task_type` INT NULL COMMENT 'See on \"runnin_number\" table',
  `task_job` INT NULL COMMENT 'Link to Master table on each task',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `laravel` ;

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_availableDevice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_availableDevice` (`id` INT, `device_no` INT, `brand` INT, `model` INT, `ip_address` INT, `description` INT, `serial_no` INT, `warranty` INT, `amount` INT, `unit_price` INT, `remark` INT, `create_user` INT, `create_date` INT, `update_user` INT, `update_date` INT, `stock_id` INT, `stock_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_availableMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_availableMaterial` (`id` INT, `material_no` INT, `brand` INT, `model` INT, `description` INT, `serial_no` INT, `amount` INT, `unit_price` INT, `create_user` INT, `create_date` INT, `update_user` INT, `update_date` INT, `stock_id` INT, `stock_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_availableStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_availableStock` (`id` INT, `stock_no` INT, `name` INT, `user_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_availableUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_availableUsers` (`id` INT, `firstname` INT, `lastname` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_sumMaterialDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_sumMaterialDetail` (`material_id` INT, `sum` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_sumLendDeviceDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_sumLendDeviceDetail` (`device_id` INT, `sum` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_sumRepairDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_sumRepairDetail` (`device_id` INT, `sum` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_sumRoombookingDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_sumRoombookingDetail` (`device_id` INT, `sum` INT);

-- -----------------------------------------------------
-- View `laravel`.`view_availableDevice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_availableDevice`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_availableDevice` AS
SELECT
d.id,
d.device_no,
d.brand,
d.model,
d.ip_address,
d.description,
d.serial_no,
d.warranty,
d.amount-(IFNULL(l.sum,0)+IFNULL(rb.sum,0)+IFNULL(rd.sum,0)) AS amount,
IFNULL(d.unit_price,0) AS unit_price,
d.remark,
d.create_user,
d.create_date,
d.update_user,
d.update_date,
d.stock_id,
s.name AS stock_name
FROM device AS d 
LEFT JOIN stock AS s ON d.stock_id=s.id
LEFT JOIN view_sumlenddevicedetail AS l ON d.id=l.device_id
LEFT JOIN view_sumroombookingdetail AS rb ON d.id=rb.device_id
LEFT JOIN view_sumrepairdetail AS rd ON d.id=rd.device_id
WHERE d.flag = '1' 
AND (l.sum < d.amount OR l.sum IS NULL) 
AND (rb.sum < d.amount OR rb.sum IS NULL) 
AND (rd.sum < d.amount OR rd.sum IS NULL) ;

-- -----------------------------------------------------
-- View `laravel`.`view_availableMaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_availableMaterial`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_availableMaterial` AS
SELECT
m.id,
m.material_no,
m.brand,
m.model,
m.description,
m.serial_no,
m.amount-IFNULL(br.sum,0) AS amount,
IFNULL(m.unit_price,0) AS unit_price,
m.create_user,
m.create_date,
m.update_user,
m.update_date,
m.stock_id,
s.name AS stock_name
FROM material AS m 
LEFT JOIN stock AS s ON m.stock_id=s.id
LEFT JOIN view_sumMaterialDetail AS br ON br.material_id=m.id
WHERE m.flag = '1'
AND (br.sum < m.amount OR br.sum IS NULL);

-- -----------------------------------------------------
-- View `laravel`.`view_availableStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_availableStock`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_availableStock` AS
SELECT s.id, s.stock_no, s.name, u.id AS user_id
FROM stock AS s
JOIN users AS u 
left JOIN user_stock AS us ON u.id=us.users_id 
	AND s.id=us.stock_id 
    AND (us.flag=1 OR us.id IS NULL)
WHERE us.id IS NULL;

-- -----------------------------------------------------
-- View `laravel`.`view_availableUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_availableUsers`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_availableUsers` AS
SELECT u.id, u.firstname, u.lastname 
FROM stock AS s
JOIN users AS u 
left JOIN user_stock AS us ON u.id=us.users_id 
	AND s.id=us.stock_id 
    AND (us.flag=1 OR us.id IS NULL)
WHERE us.id IS NULL
GROUP BY u.id;

-- -----------------------------------------------------
-- View `laravel`.`view_sumMaterialDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_sumMaterialDetail`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_sumMaterialDetail` AS
SELECT material_id, SUM(amount) AS sum 
FROM bring_material_detail
WHERE flag=1
GROUP BY material_id;

-- -----------------------------------------------------
-- View `laravel`.`view_sumLendDeviceDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_sumLendDeviceDetail`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_sumLendDeviceDetail` AS
SELECT l.device_id, SUM(amount) AS sum
FROM lend_device_detail AS l 
LEFT JOIN lend_device AS ld ON l.lend_device_id=ld.id
WHERE l.flag='1' 
AND ld.end_time > NOW()
GROUP BY l.device_id;

-- -----------------------------------------------------
-- View `laravel`.`view_sumRepairDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_sumRepairDetail`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_sumRepairDetail` AS
SELECT r.device_id, 1 AS sum
FROM repair_device_detail AS r 
LEFT JOIN repair_device AS rd ON r.repair_device_id=rd.id
WHERE r.flag='1' 
GROUP BY r.device_id;

-- -----------------------------------------------------
-- View `laravel`.`view_sumRoombookingDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_sumRoombookingDetail`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_sumRoombookingDetail` AS
SELECT b.device_id, SUM(amount) AS sum
FROM booking_room_detail AS b 
LEFT JOIN booking_room AS br ON b.booking_room_id=br.id
WHERE b.flag='1' 
AND br.end_time > NOW()
GROUP BY b.device_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
