-- MySQL Script generated by MySQL Workbench
-- 05/03/15 22:40:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`user_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_no` VARCHAR(45) NULL,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `flag` INT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `user_role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_role_id`),
  INDEX `fk_user_user_role1_idx` (`user_role_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `laravel`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`device_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`device_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_no` VARCHAR(45) NULL,
  `brand` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `ip_address` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `serial_no` VARCHAR(100) NULL,
  `warranty` VARCHAR(45) NULL,
  `amount` INT NULL,
  `unit_price` VARCHAR(45) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `stock_id` INT UNSIGNED NOT NULL,
  `device_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `stock_id`, `device_type_id`),
  INDEX `fk_device_stock1_idx` (`stock_id` ASC),
  INDEX `fk_device_devicel_type1_idx` (`device_type_id` ASC),
  CONSTRAINT `fk_device_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `laravel`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_devicel_type1`
    FOREIGN KEY (`device_type_id`)
    REFERENCES `laravel`.`device_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `material_no` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `serial_no` VARCHAR(100) NULL,
  `amount` INT NULL,
  `unit_price` VARCHAR(45) NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `stock_id` INT UNSIGNED NOT NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`, `stock_id`),
  INDEX `fk_material_stock1_idx` (`stock_id` ASC),
  CONSTRAINT `fk_material_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `laravel`.`stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_no` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`repair_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`repair_device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `repair_no` VARCHAR(45) NULL,
  `person` VARCHAR(100) NULL,
  `approvement` TINYINT(1) NULL,
  `approved_date` DATETIME NULL,
  `received_by` VARCHAR(100) NULL,
  `received_date` DATETIME NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`booking_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`booking_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `booking_no` VARCHAR(45) NULL,
  `events` VARCHAR(200) NULL,
  `purpose` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `contact_person` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `room_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `room_id`),
  INDEX `fk_booking_room_room1_idx` (`room_id` ASC),
  CONSTRAINT `fk_booking_room_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `laravel`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`lend_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`lend_device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lend_no` VARCHAR(45) NULL,
  `purpose` VARCHAR(200) NULL,
  `rent_person` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `approvement` TINYINT(1) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`mapping_computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`mapping_computer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`repair_device_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`repair_device_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_no` VARCHAR(45) NULL,
  `symptom` TEXT NULL,
  `flag` INT NULL,
  `repair_device_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `repair_device_id`, `device_id`),
  INDEX `fk_repair_device_detail_repair_device1_idx` (`repair_device_id` ASC),
  INDEX `fk_repair_device_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_repair_device_detail_repair_device1`
    FOREIGN KEY (`repair_device_id`)
    REFERENCES `laravel`.`repair_device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_device_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`lend_device_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`lend_device_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_no` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `amount` INT NULL,
  `flag` INT NULL,
  `lend_device_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `lend_device_id`, `device_id`),
  INDEX `fk_booking_device_detail_booking_device1_idx` (`lend_device_id` ASC),
  INDEX `fk_booking_device_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_booking_device_detail_booking_device1`
    FOREIGN KEY (`lend_device_id`)
    REFERENCES `laravel`.`lend_device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_device_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(45) NULL,
  `purpose` VARCHAR(200) NULL,
  `order_by` VARCHAR(100) NULL,
  `order_date` DATETIME NULL,
  `approvement` TINYINT(1) NULL,
  `approved_date` DATETIME NULL,
  `received_by` VARCHAR(100) NULL,
  `received_date` DATETIME NULL,
  `checked_by` VARCHAR(100) NULL,
  `checked_date` DATE NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`order_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_no` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `amount` INT NULL,
  `unit_price` VARCHAR(45) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  INDEX `fk_order_detail_order_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_detail_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `laravel`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`mapping_computer_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`mapping_computer_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mapping_no` VARCHAR(45) NULL,
  `computer_name` VARCHAR(100) NULL,
  `serial_no` VARCHAR(100) NULL,
  `ip` VARCHAR(45) NULL,
  `os` VARCHAR(45) NULL,
  `product_key_os` VARCHAR(45) NULL,
  `brand` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `cpu` VARCHAR(100) NULL,
  `ram` VARCHAR(100) NULL,
  `video_card` VARCHAR(100) NULL,
  `hdd` VARCHAR(100) NULL,
  `cd_dvd` VARCHAR(100) NULL,
  `antivirus` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  `flag` INT NULL,
  `mapping_computer_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `mapping_computer_id`, `device_id`),
  INDEX `fk_mapping_computer_detail_mapping_computer1_idx` (`mapping_computer_id` ASC),
  INDEX `fk_mapping_computer_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_mapping_computer_detail_mapping_computer1`
    FOREIGN KEY (`mapping_computer_id`)
    REFERENCES `laravel`.`mapping_computer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapping_computer_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`booking_room_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`booking_room_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_no` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `amount` INT NULL,
  `flag` INT NULL,
  `booking_room_id` INT UNSIGNED NOT NULL,
  `device_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `booking_room_id`, `device_id`),
  INDEX `fk_booking_room_detail_booking_room1_idx` (`booking_room_id` ASC),
  INDEX `fk_booking_room_detail_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_booking_room_detail_booking_room1`
    FOREIGN KEY (`booking_room_id`)
    REFERENCES `laravel`.`booking_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_room_detail_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `laravel`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`bring_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`bring_material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bring_no` VARCHAR(45) NULL,
  `purpose` VARCHAR(200) NULL,
  `description` VARCHAR(45) NULL,
  `withdraw_person` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `approvement` TINYINT(1) NULL,
  `remark` TEXT NULL,
  `create_user` INT NULL,
  `create_date` DATETIME NULL,
  `update_user` INT NULL,
  `update_date` DATETIME NULL,
  `flag` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`bring_material_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`bring_material_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_no` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `amount` INT NULL,
  `flag` INT NULL,
  `bring_material_id` INT UNSIGNED NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `bring_material_id`, `material_id`),
  INDEX `fk_bring_material_detail_bring_material1_idx` (`bring_material_id` ASC),
  INDEX `fk_bring_material_detail_material1_idx` (`material_id` ASC),
  CONSTRAINT `fk_bring_material_detail_bring_material1`
    FOREIGN KEY (`bring_material_id`)
    REFERENCES `laravel`.`bring_material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bring_material_detail_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `laravel`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `laravel` ;

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_availableDevice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_availableDevice` (`id` INT, `device_no` INT, `brand` INT, `model` INT, `ip_address` INT, `description` INT, `serial_no` INT, `warranty` INT, `amount` INT, `unit_price` INT, `remark` INT, `create_user` INT, `create_date` INT, `update_user` INT, `update_date` INT, `stock_id` INT, `stock_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `laravel`.`view_availableMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`view_availableMaterial` (`id` INT, `material_no` INT, `brand` INT, `model` INT, `description` INT, `serial_no` INT, `amount` INT, `unit_price` INT, `create_user` INT, `create_date` INT, `update_user` INT, `update_date` INT, `stock_id` INT, `stock_name` INT);

-- -----------------------------------------------------
-- View `laravel`.`view_availableDevice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_availableDevice`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_availableDevice` AS
SELECT
d.id,
d.device_no,
d.brand,
d.model,
d.ip_address,
d.description,
d.serial_no,
d.warranty,
d.amount,
d.unit_price,
d.remark,
d.create_user,
d.create_date,
d.update_user,
d.update_date,
d.stock_id,
s.name AS stock_name
FROM device AS d LEFT JOIN stock AS s ON d.stock_id=s.id
LEFT JOIN booking_room_detail AS b ON d.id=b.device_id
LEFT JOIN booking_room AS br ON br.id=b.booking_room_id
LEFT JOIN repair_device_detail AS r ON d.id=r.device_id
LEFT JOIN repair_device AS rd ON rd.id=r.repair_device_id
LEFT JOIN lend_device_detail AS l ON d.id=l.device_id 
LEFT JOIN lend_device AS ld ON ld.id=l.lend_device_id
WHERE d.flag = '1' 
AND (b.flag = '0' OR br.end_time <= NOW() OR b.flag IS NULL) 
AND (r.flag = '0' OR rd.received_date <= NOW() OR r.flag IS NULL) 
AND (l.flag = '0' OR ld.end_time <= NOW() OR l.flag IS NULL);

-- -----------------------------------------------------
-- View `laravel`.`view_availableMaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel`.`view_availableMaterial`;
USE `laravel`;
CREATE  OR REPLACE VIEW `view_availableMaterial` AS
SELECT
m.id,
m.material_no,
m.brand,
m.model,
m.description,
m.serial_no,
m.amount,
m.unit_price,
m.create_user,
m.create_date,
m.update_user,
m.update_date,
m.stock_id,
s.name AS stock_name
FROM material AS m LEFT JOIN stock AS s ON m.stock_id=s.id
LEFT JOIN bring_material_detail AS b ON m.id=b.material_id
WHERE m.flag = '1' 
AND (b.flag = '0' OR b.flag IS NULL);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
